safe:        false
port:        4000
baseurl:     /

source:      .
exclude:     [bower.json, Gruntfile.js, package.json, params.json, README.md, stylesheets/.*\.less ]
destination: ./_site
encoding:    UTF-8

highlighter: rouge
future:      true
lsi:         false
markdown:    kramdown
permalink:   /blog/:categories/:year/:month/:day/:title.html

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

name: It-Signal
description: A agile developer's blog
url: https://maxime.werlen.fr
author:
  name: Maxime Werlen
  email: maxime@werlen.fr
